# Generated by Django 6.0.2 on 2026-02-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_branch',
            field=models.ForeignKey(blank=True, help_text='The branch the user is currently viewing/working in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='core.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.distributor'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch_id',
            field=models.CharField(blank=True, help_text='Legacy field - will be migrated to current_branch FK', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_id',
            field=models.CharField(blank=True, help_text='Legacy field - will be migrated to branch_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('auditor', 'Auditor'), ('super_admin', 'Super Admin')], default='owner', help_text='Legacy role field - use UserRole instead', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
